### ISSUE TITLE
urn:uuid:

### ISSUE THREAD

**Issue by don** [google/uribeacon#121]
I'd like to add and example for the `urn:uuid:` protocol but I'm not sure what people would do with these. 

Can you point me to discussion or reasons for why `urn:uuid:` was added?

**Comment by schilit** [comment]
It would be a different user agent than Physical Web app. We don't have a specific use case but it is one of the URI RFCs so we wanted to see how to support it (and we can since the binary form fits within the ADV packet).

I think URIs that represent product codes like EAN, UPC, etc are more interesting than generic UUIDs. These can be sent to shopping services or search engines and result in reasonable information.
