### ISSUE TITLE
URIBeacon Reset

### ISSUE THREAD

**Issue by corymast** [google/uribeacon#170]
I have a question regarding the Lock value upon resetting the URIBeacon. The Configuration Service specification states that the reset value for the Lock should be set to all zeros.
![screen shot 2015-01-30 at 4 00 01 pm](https://cloud.githubusercontent.com/assets/9039168/5984979/159407b8-a899-11e4-85b4-913b9b8d9c4c.png)

I have flashed my device with a custom value for the Lock and if I reset the URIBeacon it will reset my Lock to all zeros instead of back to my custom lock value.

Is there a plan to implement a way to be able to set the Lock value to something other than all zeros either initially or after a reset occurs?

Thank You

**Comment by schilit** [comment]
In order to do the RESET the beacon must be unlocked, in which case there
is no lock value. Lock values are essentially single use.

If RESET changes the lock, you'll have to issue an UNLOCK before setting
the URI and then follow that with with a LOCK.. This is because LOCK
immediately sets the lock value (not on disconnect). It seems more direct
to issue the RESET, change settings, then end with a LOCK.

You can ship your beacons flashed in the lock state, but I wouldn't
recommend making that the RESET state. Are there reasons you are thinking
of a reset-default lock value?

Bill

**Comment by schilit** [comment]
Let me know if this issue is still open, otherwise I'll close it.

**Comment by corymast** [comment]
Hi Bill,

I believe this issue is closed. My confusion was thinking of the lock value as a static password instead of a key that is updated when you lock the device and cleared when you unlock the device. If I am incorrect please let me know otherwise this issue is resolved. Thank you for your help and detailed description

Cory

**Comment by schilit** [comment]
Thanks! Closing.
