### ISSUE TITLE
Informations on partnership 

### ISSUE THREAD

**Issue by Biqui** [google/uribeacon#254]
Good morning,
from the vendors page i See iBlio that,  in his website, claims to be the only strategic partner of Google outside USA for this project. So this is a Google project? Do you have partners in Germany? 

Regards

Mattew  Biqui

**Comment by valterforesto** [comment]
iBlio said in the home page: "We are the first strategic partner of Google outside the US for the whole Physical Web project" because we are the early adopters of the whole Physical Web project and made the first validated it's UriBeacon products outside of US at the end of January 2015.

Valter Foresto
www.iblio.net

**Comment by scottjenson** [comment]
URIBeacon is an open source project. There are now at least 9 companies that are participating in this new standard (with more than 1 in Europe) You don't need to be a strategic partner, you just need to implement the spec (and use the validator app ;-) As an open source project we can't have 'strategic partners', we just have 'participants'. I will contact iBiblio and ask for more information on this.

**Comment by Biqui** [comment]
Scott thanks for clarify. So project will get a new participant .
